spring:
  datasource:
    url: jdbc:mysql://localhost:3306/employee?allowPublicKeyRetrieval=true&useSSL=false
    #url: jdbc:mysql://localhost:3306/s?createDatabaseIfNotExist=true
    username: root
    password: 9090

#JPA Settings
  #jpa.hibernate.ddl_auto: create
  jpa.hibernate.ddl_auto: update
  jpa.show-sql: true